###端口号配置
server:
  port: 8080
spring:
###数据库配置
  datasource1:
    url: jdbc:mysql://localhost:3306/ruan
    username: root
    password:
    minPoolSize: 3
    maxPoolSize: 25
    maxLifetime: 20000
    borrowConnectionTimeout: 30
    loginTimeout: 30
    maintenanceInterval: 60
    maxIdleTime: 60
    testQuery: select 1
    driverClassName: com.mysql.jdbc.Driver
  datasource2:
      url: jdbc:mysql://localhost:3306/youxianqi
      username: root
      password:
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1
      driverClassName: com.mysql.jdbc.Driver
#静态页面的配置
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp